version: "2"
services:
  db:
    restart: always
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=my-password
      - POSTGRES_DB=mylocaldb
    expose:
      - "5432"
    networks:
      - desenv-network

networks:
  desenv-network:
    driver: bridge
