"""empty message

Revision ID: a40b21b341a6
Revises: 6374cfff575b
Create Date: 2018-10-10 21:37:53.636345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Integer, String, DateTime
from sqlalchemy.sql import table, column
# revision identifiers, used by Alembic.
revision = 'a40b21b341a6'
down_revision = '6374cfff575b'
branch_labels = None
depends_on = None


call = table('call',
             column('id', Integer),
             column('source_phone', String),
             column('destination_phone', String),
             column('started_date', DateTime),
             column('finished_date', DateTime),
             column('call_identifier', Integer))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('call_detail')
    op.drop_table('call_detail_type')
    op.execute(call.delete())
    op.add_column('call', sa.Column(
        'call_identifier', sa.Integer(), nullable=True))
    op.add_column('call', sa.Column(
        'finished_date', sa.DateTime(), nullable=True))
    op.add_column('call', sa.Column(
        'started_date', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'call', ['call_identifier'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'call', type_='unique')
    op.drop_column('call', 'started_date')
    op.drop_column('call', 'finished_date')
    op.drop_column('call', 'call_identifier')
    op.create_table('call_detail_type',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text(
                        "nextval('call_detail_type_id_seq'::regclass)"), autoincrement=True, nullable=False),
                    sa.Column('description', sa.VARCHAR(length=120),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint(
                        'id', name='call_detail_type_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('call_detail',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('detail_type_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('date_added', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=False),
                    sa.Column('call_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['call_id'], ['call.id'], name='call_detail_call_id_fkey'),
                    sa.ForeignKeyConstraint(['detail_type_id'], [
                        'call_detail_type.id'], name='call_detail_detail_type_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='call_detail_pkey')
                    )
    # ### end Alembic commands ###
