"""empty message

Revision ID: bafabf103994
Revises: a40b21b341a6
Create Date: 2018-10-11 01:30:23.582783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bafabf103994'
down_revision = 'a40b21b341a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call', 'price')
    # ### end Alembic commands ###
